{% set name = 'bob.learn.em' %}

package:
  name: {{ name }}
  version: {{ environ.get('BOB_PACKAGE_VERSION', '0.0.1') }}

build:
  number: {{ environ.get('BOB_BUILD_NUMBER', 0) }}
  script:
    - cd {{ environ.get('CI_PROJECT_DIR', environ.get('RECIPE_DIR') + '/..') }}
    {% if environ.get('BUILD_EGG') %}
    - python setup.py sdist --formats=zip
    {% endif %}
    - pip install .
    - sphinx-build -W doc $PREFIX/docs/{{ name }}
  script_env:
   - BOB_DOCUMENTATION_SERVER

requirements:
  build:
    - python
    - setuptools
    - toolchain {{ toolchain }}
    - sphinx
    - sphinx_rtd_theme
    - bob.extension
    - bob.blitz
    - bob.core >2.0.5
    - bob.io.base
    - bob.sp
    - bob.math
    - bob.learn.activation
    - bob.learn.linear
    - cmake
    - pkg-config
    - libblitz {{ libblitz }}
    - boost {{ boost }}
    - numpy {{ numpy }}
    - gcc {{ gcc }}  # [linux]
    - libgcc {{ libgcc }}  # [linux]
  run:
    - python
    - setuptools
    - bob.extension
    - bob.blitz
    - bob.core >2.0.5
    - bob.io.base
    - bob.sp
    - bob.math
    - bob.learn.activation
    - bob.learn.linear
    - libblitz
    - boost
    - {{ pin_compatible('numpy', min_pin='x.x', max_pin='x.x') }}
    - libgcc  # [linux]

test:
  imports:
    - {{ name }}
  commands:
    - nosetests --with-coverage --cover-package={{ name }} -sv {{ name }}
    # The doctests will run only if "CI_PROJECT_DIR" is available as an
    # environment variable. If you are testing locally, you can set it to the
    # root of your project.
    - sphinx-build -b doctest {{ environ.get('CI_PROJECT_DIR') }}/doc sphinx
  requires:
    - nose
    - coverage
    - sphinx
    - sphinx_rtd_theme

about:
  home: https://www.idiap.ch/software/bob/
  license: BSD 3-Clause
  summary: Bindings for emelaneous machines and trainers of Bob
  license_family: BSD
